# Generated by Django 2.2 on 2019-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, editable=False, max_length=300)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
